### ISSUE TITLE
Tidak tampil apa apa

### ISSUE THREAD

**Issue by RaplesWojtyla** [refaelsiagian/Tugas-Praktikum#1]
Bang ini ngebug ya. Pas saya jalankan tidak menampilkan apa-apa!!!

**Comment by refaelsiagian** [comment]
Emang belum ada apa-apa

**Comment by refaelsiagian** [comment]
> Bang ini ngebug ya. Pas saya jalankan tidak menampilkan apa-apa!!!

Emang belum ada apa-apa

**Comment by RaplesWojtyla** [comment]
Routenya error bang
